version: "3.3"
services:
  postgresql:
    image: postgres:12.14-alpine3.17
    environment:
      POSTGRES_USER: "perfectly_spoken"
      POSTGRES_PASSWORD: "perfectly_spoken"
      POSTGRES_DB: "perfectly_spoken"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  resapp:
    build: .
    hostname: residence
    restart: always
    user: www-data
    ports:
      - '3000:8000'
      - '5000:80'
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes

volumes:
  postgresql-data:
